### ISSUE TITLE
[Suggest] Added a player skull drop chance

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [orewaee/PlayerHeads#1]
Added a player skull drop chance option to the configuration file, which prevents players from getting bored with frequently dropped skulls, and also increases the collection value of the skull
That's all, and thanks for your reply!

**Comment by orewaee** [comment]
Hello, thanks for the idea. Implemented in version [`v0.1.2`](https://github.com/orewaee/PlayerHeads/releases/tag/v0.1.2).

**Comment by xiaoyueyoqwq** [comment]
> Hello, thanks for the idea. Implemented in version [`v0.1.2`](https://github.com/orewaee/PlayerHeads/releases/tag/v0.1.2).

Got it, have a nc day :P
